'use strict';(function(d){function c(){this._events={};this._maxListeners=10}function a(b,a,e,c,d){this.type=b;this.listener=a;this.scope=e;this.once=c;this.instance=d}a.prototype.fire=function(b){this.listener.apply(this.scope||this.instance,b);if(this.once)return this.instance.removeListener(this.type,this.listener,this.scope),!1};c.prototype.eachListener=function(b,a){var e=null,c=null,d=null;if(this._events.hasOwnProperty(b)){c=this._events[b];for(e=0;e<c.length;e+=1)if(d=a.call(this,c[e],e),
!1===d)e-=1;else if(!0===d)break}return this};c.prototype.addListener=function(b,f,e,c){this._events.hasOwnProperty(b)||(this._events[b]=[]);this._events[b].push(new a(b,f,e,c,this));this.emit("newListener",b,f,e,c);this._maxListeners&&!this._events[b].warned&&this._events[b].length>this._maxListeners&&("undefined"!==typeof console&&console.warn("Possible EventEmitter memory leak detected. "+this._events[b].length+" listeners added. Use emitter.setMaxListeners() to increase limit."),this._events[b].warned=
!0);return this};c.prototype.on=c.prototype.addListener;c.prototype.once=function(b,a,e){return this.addListener(b,a,e,!0)};c.prototype.removeListener=function(b,a,e){this.eachListener(b,function(c,d){c.listener===a&&(!e||c.scope===e)&&this._events[b].splice(d,1)});this._events[b]&&0===this._events[b].length&&delete this._events[b];return this};c.prototype.off=c.prototype.removeListener;c.prototype.removeAllListeners=function(b){b&&this._events.hasOwnProperty(b)?delete this._events[b]:b||(this._events=
{});return this};c.prototype.listeners=function(b){if(this._events.hasOwnProperty(b)){var a=[];this.eachListener(b,function(b){a.push(b.listener)});return a}return[]};c.prototype.emit=function(b){for(var a=[],e=null,e=1;e<arguments.length;e+=1)a.push(arguments[e]);this.eachListener(b,function(b){return b.fire(a)});return this};c.prototype.setMaxListeners=function(a){this._maxListeners=a;return this};"function"===typeof define&&define.amd?define(function(){return c}):d.EventEmitter=c})(this);
StackExchange.realtime=function(){function d(a){StackExchange.options.user.isDeveloper&&console.log(a)}function c(){p.on("hb",function(a){k.send(a)})}function a(a){l?(d("sending: "+a),k.send(a)):m.push(a)}function b(a,b){1!=$("#vote-accepted-"+a.answerid).length&&($(".vote-accepted-on").remove(),b||$('.vote input[value="'+a.answerid+'"]').parent().append('<span class="vote-accepted-on" title="The question owner accepted this as the best answer">accepted</span>'))}function f(){$("#new-post-activity").remove();
$("#answers-header").prepend(q)}function e(a,b){return a.index<b.index?-1:a.index>b.index?1:0}function g(){$("#new-post-activity").remove();var a=h.sort(e),b;for(b in a){var c=a[b];$("#question-summary-"+c.id).remove();$(c.body).prependTo("#question-mini-list, #questions").hide().fadeIn()}i(0);null!=StackExchange.options.user.accountId&&StackExchange.tagPreferences.applyPrefs(!0,u);"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);h=[]}function i(a){var b=document.title.replace(/^\(\d*\*?\) /,
"");0<a&&(b="("+a+") "+b);window.setTimeout(function(){$(document).attr("title",b)},200)}var j,k,h=[],n=[],o=0,m=[],l=!1,u,p=new EventEmitter,q=function(){var a=Object.keys(n).length;return $('<div id="new-post-activity">'+a+" new answer"+(1<a?"s":"")+" to this question</div>").click(function(){StackExchange.realtime.expandAnswers()})},t=function(){var a=Object.keys(h).length;i(a);return $('<div id="new-post-activity">'+a+" question"+(1<a?"s":"")+" with new activity</div>").click(function(){StackExchange.realtime.expandActiveQuestions()})};
return{init:function(a){j=a;if("WebSocket"in window||"MozWebSocket"in window){if(k)try{d("closing WebSocket"),k.close()}catch(b){}k||(d("opening WebSocket"),k="WebSocket"in window?new WebSocket(j):new MozWebSocket(j),k.onopen=function(){if(!l){l=!0;for(var a=0,b=m.length;a<b;a++)d("sending: "+m[a]),k.send(m[a]);m=[]}d("WebSocket opened");c()},k.onmessage=function(a){a=$.parseJSON(a.data);p.emit(a.action,a.data)},k.onclose=function(){k=null;d("WebSocket closed");5>o&&(o++,d("reconnect attempt:"+o),
setTimeout('StackExchange.realtime.init("'+j+'")',500))},k.onerror=function(){d("WebSocket failed");k=null})}},expandActiveQuestions:g,expandAnswers:function(){var a=$("#answers #answers-header .answers-subheader h2"),b=parseInt(a.text().match(/^\d*\*?/))+n.length;isNaN(b)&&(b=n.length);a.text(b+" Answer"+(1<b?"s":""));$("#new-post-activity").remove();var e=$("#answers #answers-header");$.each(n,function(a,b){$.get("/posts/"+b+"/ajax-load-mini",function(a){a=$(a);a.insertAfter(e).hide().fadeIn(400,
function(){"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub])});StackExchange.comments.init({post:a});StackExchange.vote.init(b)})});StackExchange.vote||StackExchange.question.bindAnonymousVoteDisclaimers();e.find("a[id^='link-post-']").click(function(a){if(!a.ctrlKey&&!a.metaKey)return StackExchange.question.showShareTip($(this),options.showCitation),!1});StackExchange.question.bindSuggestedEditPopupLinks();StackExchange.question.canViewVoteCounts&&StackExchange.vote.bindFetchVoteCounts();
StackExchange.question.initShareLinks();"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);n=[]},subscribeToActiveQuestions:function(b,e,c,f,d){b=b+"-"+e;u=c;a(b);p.on(b,function(a){a=$.parseJSON(a);if(null!=d)for(var b=0;b<d.length;b++)if(-1==$.inArray(d[b],a.tags))return;null!=StackExchange.options.user.accountId&&StackExchange.tagPreferences.isIgnored(a.body)||(h[a.id]={id:a.id,body:a.body,index:(new Date).getTime()},$("#new-post-activity").remove(),$("#question-mini-list, #questions").prepend(t),
f&&g())})},subscribeToInboxNotifications:function(){if(null!=StackExchange.options.user.accountId){var b=StackExchange.options.user.accountId+"-inbox";a(b);p.on(b,function(a){$(".unreadCount").remove();var b=$('<a class="unreadCount" title="unread messages in your inbox">'+a+"</a>").insertAfter(".genu");$("#portalLink .unreadCount").css({marginTop:b.css("margin-top"),opacity:1},2E3);genuwine.setUnreadCount(a)})}},subscribeToQuestion:function(e,c){var h=e+"-question-"+c;a(h);p.on(h,function(a){a=$.parseJSON(a);
switch(a.a){case "score":var e=$('.vote input[value="'+a.id+'"]').siblings(".vote-count-post");e.text()!=a.score&&(e.text(a.score),0==$(":animated").length&&e.fadeTo("fast",0.7).fadeTo("fast",1),StackExchange.question.canViewVoteCounts()&&StackExchange.vote.bindFetchVoteCounts());break;case "comment-add":0==$("#comment-"+a.commentid).length&&(a=$("#comments-link-"+a.id),e=a.data("comments-count")||0,e++,a.data("comments-count",e),a.html("add / show <b>"+e+"</b> more comment"+(1<e?"s":"")).show().fadeTo("fast",
0.7).fadeTo("fast",1));break;case "answer-add":0==$("#answer-"+a.answerid).length&&(n.push(a.answerid),StackExchange.cardiologist.isHeartBeating()?StackExchange.helpers.DelayedReaction(f,5E3).trigger():f(),StackExchange.cardiologist.notifiedOfNewAnswer());break;case "accept":b(a);break;case "unaccept":b(a,!0)}})},subscribeToReputationNotifications:function(b){null!=StackExchange.options.user.accountId&&(b=b+"-"+StackExchange.options.user.userId+"-reputation",a(b),p.on(b,function(a){var b=$("#hlinks .reputation-score");
b.text()!=a.score&&(0==$(":animated").length&&b.fadeTo("fast",0.8).fadeTo("fast",1),b.text(a))}))}}}();"use strict";StackExchange.anonymous={};
var gauth=function(){return{informStackAuth:function(d){if(gauth.enabled()){var c=document.domain;"meta."==c.substr(0,5)&&(c=c.substr(4,c.length-4));var a=$.cookie("gauth");if(null==a)$.cookie("gauth",null,{path:"/",domain:c}),$.cookie("gauth",null,{path:"/",domain:document.domain});else{"."!=c.charAt(0)&&(c="."+c);$.cookie("gauth",null,{path:"/",domain:c});$.cookie("gauth",null,{path:"/",domain:document.domain});var b=a.indexOf(":"),c=a.substr(0,b),a=a.substr(b+1),f=d+"/auth/global/write?authToken="+
encodeURIComponent(c)+"&nonce="+encodeURIComponent(a);$(document).ready(function(){$("#footer").append("<iframe style='display:none' src='"+f+"'></iframe>")})}}},checkStackAuth:function(d){if(gauth.enabled()&&null==$.cookie("gauthed")){$.cookie("gauthed","1",{path:"/"});var c=function(a){if(a.origin==d)if("No Local Storage"==a.data)gauth.noGAuthStorage();else if("No Session"==a.data)gauth.noGAuthSession();else{var b=a.data.substr(0,a.data.indexOf(",")),a=a.data.substr(a.data.indexOf(",")+1);$.post("/users/login/global",
{authToken:b,nonce:a},function(a){gauth.globallyAuthed(a)},"json")}};window.attachEvent?window.attachEvent("onmessage",c):window.addEventListener("message",c,!1);$.post("/users/login/global/request","",function(a){var b=d+"/auth/global/read?request="+encodeURIComponent(a.token)+"&nonce="+encodeURIComponent(a.nonce);$(document).ready(function(){$("#footer").append("<iframe id='global-auth-frame' style='display:none' src='"+b+"'></iframe>")})},"json")}},enabled:function(){$.cookie("enabledCheck","1");
if(null==$.cookie("enabledCheck"))return!1;$.cookie("enabledCheck",null);return"undefined"==typeof localStorage?!1:!0},noGAuthStorage:function(){},noGAuthSession:function(){},globallyAuthed:function(d){if(d&&d.Message){var d=d.Message+" ",c,a=!1,b=""+window.location,f=b.indexOf("returnurl=");if(-1!=f){var e=b.indexOf("&",f);-1==e&&(e=b.length);c=decodeURIComponent(b.substring(f+10,e));c=/^(?:http:\/\/|\/)/.test(c)?c.replace(/[^-a-z0-9+&@#\/%?=~_|!:,.;()]/g,""):null}-1!=b.indexOf("/users/login")&&
(a=!0,c=c||"/");StackExchange.helpers.showFancyOverlay({message:a?d+"<br>You are being redirected...":d+(c?"<a href=\"javascript:window.location='"+c+"'\">Click here</a> to return to your last location.":'<a href="javascript:location.reload(true)">Click here</a> to refresh the page.'),showClose:!a,complete:function(){a&&(window.location=c)}})}}}}(),genuwine=function(){var d,c="",a,b,f=function(){return $(".genu").hasClass("genu-on")},e=function(){var e=$(".genu"),c=$("#seWrapper");if(0==c.length){g();
var c=$("#seWrapper"),f;0<a?(f=$("#seTabInbox"),l(f)):b?(f=$("#seTabNotices"),i(f)):(f=$("#seTabHot"),h(f));f.addClass("seCurrent")}(f=e.hasClass("genu-on"))?($(".unreadCountTab").hide(),$(".itemBoxNew").removeClass("itemBoxNew"),c.fadeOut("fast")):(c.fadeIn("fast"),$(".unreadCount").hide());e.toggleClass("genu-on",!f);-1==a&&$(e).ready(function(){$("#seTabInbox").hide()})},g=function(){var a='<div id="seWrapper" style="position:absolute; display:none;"><div class="seIntro"><a href="'+c+'">Stack Exchange</a> is a network of free, community-driven Q&A sites.</div><div class="seNav"><ul class="seNavLinks"><li><a id="seTabHot">Hot Questions</a></li><li><a id="seTabSites">All Sites</a></li><li><a id="seTabInbox">Inbox</a></li>'+
(StackExchange.options.user.isDeveloper?'<li><a id="seTabNotices">Notices</a></li>':"")+'</ul></div><div class="seContainer"></div><div class="seFooter"><div id="seTabEmail" class="seEmailAccount"><a>email settings</a></div><a id="seClose">close</a></div></div>',b=$("#hlinks"),b=b.height()+b.offset().top+5;$(a).appendTo("#portalLink").css({top:b}).find("ul.seNavLinks a, #seTabEmail").click(function(){var a=$(this);$(".seNavLinks a").removeClass("seCurrent");a.addClass("seCurrent");switch(a.attr("id")){case "seTabHot":h(a);
$("#seContainerSites, #seContainerInbox, #seContainerEmail, #seContainerNotices").hide();$("#seContainerHot").fadeIn("fast");break;case "seTabSites":0==$("#seContainerSites").length&&k(a);$("#seContainerHot, #seContainerInbox, #seContainerEmail, #seContainerNotices").hide();$("#seContainerSites").fadeIn("fast");break;case "seTabInbox":l(a);$("#seContainerHot, #seContainerSites, #seContainerEmail, #seContainerNotices").hide();$("#seContainerInbox").fadeIn("fast");break;case "seTabEmail":0==$("#seContainerEmail").length&&
n(a);$("#seContainerHot, #seContainerSites, #seContainerInbox, #seContainerNotices").hide();$("#seContainerEmail").fadeIn("fast");break;case "seTabNotices":i(a),$("#seContainerHot, #seContainerSites, #seContainerInbox, #seContainerEmail").hide(),$("#seContainerNotices").fadeIn("fast")}});$("#seClose").live("click",e)},i=function(a){0==$("#seContainerNotices").length&&q(a,"/notices/genuwine?userId="+StackExchange.options.user.id,"jsonp",j,!0)},j=function(a,b){for(var e='<div id="seContainerNotices" style="display:none">',
c=0;c<b.length;c++)var f=b[c],e=e+('<div class="noticeBox'+(f.is_unread?" itemBoxNew":"")+'"><div><p>'+f.text+"</p></div></div>");t(a,e+"</div>")},k=function(a){q(a,c+"/genuwine/sites?callback=?&host="+document.location.host+(d?"&accountId="+d:""),"jsonp",m)},h=function(a){0==$("#seContainerHot").length&&q(a,c+"/genuwine?callback=?","jsonp",o)},n=function(a){q(a,"/accounts/email-settings","json",function(a,b){function e(){$("#email-save").removeAttr("disabled");$("#email-confirmation").html("")}t(a,
'<div id="seContainerEmail" style="display:none; font-size:11px;"><div class="itemBox" style="border-bottom: 0px"><p>Would you like to receive unread inbox notifications via email?</p><div>Email: <input id="email-notify" name="email-notify" style="width:300px;" value="'+b.verifiedEmail+'"></input></div><div><input type="radio" name="optIn" value="true" id="email-enable"'+(!0==b.optIn?'checked="checked"':"")+'"> <label for="email-enable">Email me my unread inbox messages </label> <select id="email-freq"><option value="3">every 3 hours</option><option value="24">daily</option><option value="168">weekly</option></select> </div><div><input type="radio" name="optIn" value="false" id="email-disable"'+
(!0!=b.optIn?'checked="checked"':"")+'"> <label for="email-disable">Do not email me inbox messages</label></input></div><div><input type="button" name="save" id="email-save" value="Save" disabled="disabled"></input></div><div id="email-confirmation" style="display:none;"></div></div></div>');$("#email-freq").val(b.freq).on("click focus",function(){$("#email-enable").prop("checked",!0)});$("#email-notify").focus().keyup(e);$("#email-enable, #email-disable, #email-freq").change(e);$("#email-save").click(function(){v();
$.post("/accounts/verified-email-set",{email:$("#email-notify").val(),fkey:StackExchange.options.user.fkey,optin:$("input[name=optIn]:checked").val(),freq:$("#email-freq").val()},function(a){StackExchange.helpers.removeSpinner();$("#email-confirmation").html(a.message).fadeIn();a.success&&$("#email-save").attr("disabled","disabled")},"json")})},!0)},o=function(a,b){for(var e=$("<div/>"),c='<div id="seContainerHot" style="display:none">',f=0;f<b.length;f++)var h=b[f],d=h.SiteId,j='href="http://'+d+
"/q/"+h.Id+'?hq=1"',g=parseInt(h.DisplayScore,10),c=c+('<div class="itemBox"><a '+j+' class="seNumAnswer">'+g+'</a><div class="siteInfo"><p><a '+j+">"+e.text(h.Title).html()+'</a></p><a href="http://'+d+'" class="siteLink">'+d+"</a></div></div>");t(a,c+"</div>")},k=function(a){q(a,c+"/genuwine/sites?callback=?&host="+document.location.host+(d?"&accountId="+d:""),"jsonp",m)},m=function(a,b){for(var e='<div id="seContainerSites" style="display:none">',c=0;c<b.length;c++)var f=b[c],h=f.Name,d='href="http://'+
f.Id+'?as=1"',e=e+('<div class="itemBox"><a '+d+' class="siteFavicon"><img src="'+f.FaviconUrl+'" alt="'+h+'"></a><div class="siteInfo"><p><a '+d+">"+h+"</a></p><a "+d+' class="siteLink">'+f.Description+"</a></div></div>");t(a,e+"</div>")},l=function(b){-1!=a&&(0==$("#seContainerInbox").length&&q(b,"/inbox/genuwine","json",u,!0),0<a&&0==b.find(".unreadCountTab").length&&b.prepend('<span class="unreadCountTab">'+a+"</span>"))},u=function(a,b){for(var e='<div id="seContainerInbox" style="display:none">',
c=0;c<b.length;c++){var f=b[c],h='href="'+f.Url+'"',j='title="'+f.CreationDate+'"',g=f.Count,e=e+('<div class="itemBox'+(f.IsNew?" itemBoxNew":"")+'"><a '+h+' class="siteLinkFavicon"><img src="'+f.FaviconUrl+'" alt="'+f.SiteUrl+'"></a><div class="siteInfo">');"careers message"==f.Type?e+="<p><a "+h+' style="font-weight:normal"><b>'+f.Title+"</b> wants to contact you on <b>Stack Overflow Careers</b></a></p>":"invitation"==f.Type?(j=f.Count,e+="<p><a "+h+' style="font-weight:normal"><b>'+j+"</b> "+
("invitation"+(1<j?"s":""))+" awarded on <b>Stack Overflow Careers</b></a></p>"):e+="<p>"+(1<g?g+" ":"")+f.Type+" on <a "+h+" "+j+">"+f.Title+"</a></p>";e+='<p class="inboxSummary">'+(f.Summary||"")+"</p></div></div>"}d&&5<=b.length&&(e+='<div class="itemMoreContainer"><div class="seIntro"><a href="http://stackexchange.com/users/'+d+'?tab=inbox">more inbox messages &hellip;</a></div></div>');t(a,e+"</div>")},p={},q=function(a,b,e,c,f){var h=a.attr("id");if(p[h])v();else{p[h]=!0;v();var d=function(){p[h]=
!1;StackExchange.helpers.showErrorPopup($(".seContainer"),"An error occurred while loading - please try again.")};$.ajax({type:"GET",url:b,dataType:e,success:function(b){b&&(0<b.length||f)?c(a,b):d()},error:d,complete:StackExchange.helpers.removeSpinner()})}},t=function(a,b){var e=$(b);e.appendTo(".seContainer");a.hasClass("seCurrent")&&e.fadeIn("fast")},v=function(){StackExchange.helpers.removeSpinner();StackExchange.helpers.addSpinner(".seContainer",{position:"relative",left:"10px",top:"10px"})},
r=function(){var a=$("#portalLink .unreadCount"),b=a.css("margin-top");a.css({marginTop:-20,opacity:0}).show().animate({marginTop:b,opacity:1},2E3)},s=function(){!(0<a)&&StackExchange.options.user.isDeveloper&&(b=!0,$("#portalLink .unreadCount").text("\u25cf").addClass("newNotices").click(function(){$(".genu").click()}).show())};return{isVisible:f,click:e,setUnreadCount:function(b){a=b;0<b?($("#portalLink .unreadCount").text(a).click(function(){$(".genu").click()}).show(),r()):$("#portalLink .unreadCount").text("").hide();
$("#portalLink .unreadCount").removeClass("newNotices")},animateInbox:r,init:function(b,h,j){var g=$(".genu");1<=g.length&&(g[0].onclick=null);d=b;c=g.attr("href");a=h;j&&s();g.removeAttr("href").add(".unreadCount").click(e);$(document).click(function(a){f()&&!$.contains($("#portalLink")[0],a.target)&&e()})}}}();
StackExchange.notify=function(){function d(a,b){var e=$("#dismissed-messages");e.val(e.val()+"~"+a+(b?" "+b:"")+"~")}function c(a,b){var e=$("#dismissed-messages").val();return!e?!1:RegExp("~"+a+(b?" "+b:"")+"~").test(e)}function a(a,b,e){var c=parseInt($("body").css("margin-top").match(/\d+/)),a=b*c/a;e?$("body:not(.no-message-slide)").animate({marginTop:a+"px"},"fast","linear"):$("body:not(.no-message-slide)").css("marginTop",a+"px")}var b=0,f=function(e,c){var f=$("#notify-"+e+(c?"-"+c:""));-1==
e?$.cookie("m","0",{expires:90,path:"/"}):-1<e&&$.post("/messages/mark-as-read",{messagetypeid:e,id:c?c:null});d(e,c);b--;f.fadeOut("fast",function(){a(b+1,b,!0);f.remove()})},e=function(a){if(StackExchange.options.user.isDeveloper)return!0;b++;if(c(a.messageTypeId,a.id))return!1;var e="";a.messageTypeId&&(e=' id="notify-'+a.messageTypeId+(a.id?"-"+a.id:"")+'"');e="<div"+e+' style="display:none"><span class="notify-close"><a title="dismiss this notification">&times;</a></span><span class="notify-text">'+
a.text+"</span>";if(a.showProfile)var h=encodeURIComponent("/users/"+a.userId+"?tab=activity"),e=e+(' See your <a href="/messages/mark-as-read?messagetypeid='+a.messageTypeId+"&returnurl="+h+'">profile</a>.');e=$(e+"</div>");e.find(".notify-close").click(function(){a.close&&a.close();f(a.messageTypeId,a.id)});$("#notify-container").append(e);return!0},g=function(){$("#notify-container div").fadeIn("slow")},i=function(a,b){var c=$('<div class="link-more"><a>view '+a+" more notification"+(1!=a?"s":
"")+"</a></div>");$("#notify-container").append(c);c.click(function(){c.detach();for(var a=0;a<b.length;a++)e(b[a]);g()})};return{showMessages:function(c,f){for(var h=0,d=f?2:c.length,o=0;o<d&&o<c.length;o++)e(c[o])&&h++;a(b,h,!1);g();f&&h<c.length&&(d=c.slice(d),i(c.length-h,d))},show:function(a,b){$("body:not(.no-message-slide)").animate({marginTop:"2.5em"},"fast","linear");e({text:a,messageTypeId:b});g()},close:f,getMessageText:function(a){return $("#notify-"+a+" .notify-text").text()}}}();
function moveScroller(){var d=$("#scroller").width(),c=function(){var a=$(window).scrollTop(),b=$("#scroller-anchor").offset().top,c=$("#scroller");a>b?c.height()>$(window).height()?c.css({position:"fixed",top:"",bottom:"0px",width:d}):c.css({position:"fixed",top:"0px",bottom:"",width:d}):a<=b&&c.css({position:"relative",top:"",bottom:""})};$(window).scroll(c).resize(c);c()}
var styleCode=function(){return function(){"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);var d=!1;$("pre code").parent().each(function(){$(this).hasClass("prettyprint-override")&&($(this).removeClass("prettyprint-override").addClass("prettyprint"),d=!0);var c;if(c=!$(this).hasClass("prettyprint")){c=$(this);var a=$("#prettify-lang").text();""!=a?(c.addClass(a),c=!0):c=!1}c&&($(this).addClass("prettyprint"),d=!0)});d&&("undefined"!=typeof jtab?jtab.renderimplicit():StackExchange.using("prettify",
function(){StackExchange.prettify.applyCodeStyling()}))}}();
StackExchange.helpers.MagicPopup=function(d){function c(b,e){var c=$("<div id='"+d.id+"'/>").html(e),g=$("<div />").css({overflow:"hidden",position:"absolute",width:1,height:1,top:0,left:0}).append(c).appendTo("body"),i=d.showing(b,c),m={left:i.left};i.hasOwnProperty("bottom")?(m.bottom=i.bottom,m.top="auto"):m.top=i.top;var l;d.shown&&(l=function(){d.shown(b,c)});g.css(m).animate({height:c.outerHeight()+8,width:c.outerWidth()+8},300,l);a=function(){g.stop().remove();d.removed&&d.removed(b,c);a=f=
null};f=StackExchange.helpers.DelayedReaction(a,5);m=g;i.additional&&(m=m.add(i.additional));m.hover(f.cancel,f.trigger)}var a,b,f,e,g={},i=StackExchange.helpers.DelayedReaction(function(b,f){if(!e&&b){var h;d.cache&&"c_"+b in g?h=$.Deferred().resolve(g["c_"+b]):(h=$.ajax({type:"GET",url:b,dataType:"html"}),d.cache&&h.done(function(a){g["c_"+b]=a}));h.done(function(b){a&&a();""!=b&&c(f,b)})}},500);$(document).delegate(d.selector,{mouseenter:function(){if(f&&this===b)f.cancel();else return b=this,
i.trigger(d.getUrl(this),this),e=!1},mouseleave:function(){e=!0;i.cancel();f&&f.trigger()}})};
StackExchange.tagmenu=function(){function d(a){var a=$(a),b=a.attr("href");if(!b||"/"!=b.charAt(0))return null;b=a.text();if(-1<b.indexOf("*"))return null;a.attr("title","");return"/tags/"+encodeURIComponent(b)+"/subscriber-info"}function c(a,b){var c=$(a),d=c.offset(),j=c.outerHeight(),c={left:d.left},k=d.top+j,j=d.left+b.outerWidth();b.height()+k>$(window).height()+$(window).scrollTop()?c.bottom=$(window).height()-d.top-8:c.top=k;d=Math.max(1024,$(window).width());j>d&&(c.left-=j-d);return c}var a,
b;return{init:function(f){a=f;b||(b=!0,StackExchange.options.isMobile||(StackExchange.helpers.MagicPopup({selector:".post-tag:not(.user-tag)",id:"tag-menu",getUrl:d,showing:c,shown:function(b,c){a&&a(c,$(b).text())}}),$("#interesting-tags .post-tag").addClass("user-tag")))}}}();
StackExchange.usermenu=function(){function d(a,c){var d=$(a).find("img:first"),i=d.offset(),j=d.height(),k=d.width(),h=Math.max(k,j),n=64*j/h,h=64*k/h,o=c.find("img:first").css({width:h,height:n}),m=o.offset();o.css("visibility","hidden");b=d.clone().css({position:"absolute",zIndex:300,left:i.left,top:i.top,width:k,height:j}).appendTo("body");var l=function(){o[0].complete?(o.css("visibility","visible"),b.fadeOutAndRemove()):setTimeout(l,500)};b.animate({width:h,height:n,top:i.top+m.top},200,l);return{top:i.top,
left:i.left-m.left,additional:b}}function c(){b.remove()}var a,b;return{init:function(){a||(a=!0,StackExchange.options.isMobile||StackExchange.helpers.MagicPopup({selector:".user-hover .user-gravatar48, .user-hover .user-gravatar32",getUrl:function(a){a=/\/users\/([^/]+).*$/.exec($(a).closest(".user-hover").find(".user-details a").attr("href"));return!a?null:"/users/user-info/"+a[1]},cache:!0,id:"user-menu",showing:d,removed:c}))}}}();
StackExchange.chatAd=function(){function d(){var a=$(".question .post-taglist .post-tag");return!a.length?null:a.map(function(a,b){return $(b).text()}).get().join(" ")}function c(a){return 10>a?"0"+a:a}function a(a){var b=new Date;b.setTime(1E3*a);return[b.getUTCFullYear(),"-",c(b.getUTCMonth()+1),"-",c(b.getUTCDate())," ",c(b.getUTCHours()),":",c(b.getUTCMinutes()),":",c(b.getUTCSeconds()),"Z"].join("")}function b(a){var b=Math.floor((new Date).getTime()/1E3)-a,e=b%60,d=Math.floor(b/60),f=Math.floor(b/
3600);if(1>b)return"just now";if(60>b)return 1==e?"1 sec ago":e+" secs ago";if(3600>b)return 1==d?"1 min ago":d+" mins ago";if(86400>b)return 1==f?"1 hour ago":f+" hours ago";b=Math.floor(b/86400);if(1==b)return"yesterday";if(2>=b)return b+" days ago";a=new Date(1E3*a);return l[a.getMonth()]+" "+a.getDate()+" at "+a.getHours()+":"+c(a.getMinutes())}function f(a){var b=$("<div />");b.text(a);return b.html().replace('"',"&quot;")}function e(){$.get(h,null,function(a,b,c){j(a,b,c)})}function g(a){for(var c=
$('<div class="ad502-users" />'),e=0;e<a.length&&7>e;e++){var d=a[e],f=d.name;d.lastPost&&(f+=": "+b(d.lastPost));var h="http://www.gravatar.com/avatar/"+d.emailhash+"?s=23&d=identicon&r=PG",d=$('<a href="'+(k+"/users/"+d.id)+'" />');$("<img />").attr("title",f).attr("src",h).appendTo(d);c.append(d)}return c}function i(a){var b=a.user;return(a=a.userid)?'<a href="'+k+"/users/"+a+'">'+f(b)+"</a>":f(b)}function j(c){var d=$("#ad502-rooms");if(!c.error){d.html("");for(var h=c.rooms,j=0;j<h.length&&2>
j;j++){var l=h[j],r=k+"/rooms/"+l.id,s=$('<div class="ad502-room"></div>');s.append($('<h3 class="ad502-room-h3"><span class="ad502-room-title" title="'+f(l.name)+'"><a href="'+r+'">'+f(l.name)+"</a></span></h3>"));l.messages&&0<l.messages.length&&s.append($('<span title="'+a(l.lastPost)+'" class="ad502-last-message">'+b(l.lastPost)+" - "+i(l.messages[0])+"</span><br>"));l.singleImage?s.append($('<div class="ad502-users"><img src="'+k+"/rooms/users/"+l.id+'.jpeg" /></div>')):s.append(g(l.users));
d.append(s)}1<c.activeUsers?$("#h-chat-link").text(c.activeUsers+" People Chatting"):$("#h-chat-link").text("Visit Chat");$("#h-chat-link").attr("title",c.activeUsers+" users active in "+c.activeRooms+" rooms the last 60 minutes")}n<=m&&window.setTimeout(e,1E3*n);n+=o}var k,h,n=180,o=30,m=480,l="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");/^\/questions\/\d+/i.test(window.location.pathname)&&(m=0);return{init:function(a){k=a.chatUrl;h=a.reloadUrl;if(a.tagBased){var b=d();if(!b)return;
h+=(/\?/.test(h)?"&":"?")+"tags="+encodeURIComponent(b)}null===a.preloadData?e():j(a.preloadData,null,null)}}}();
StackExchange.helpers.noDiacritics=function(){var d={"\u00e0\u00e5\u00e1\u00e2\u00e4\u00e3\u00e5\u0105":"a","\u00e8\u00e9\u00ea\u00eb\u0119":"e","\u00ec\u00ed\u00ee\u00ef\u0131":"i","\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u0151":"o","\u00f9\u00fa\u00fb\u00fc":"u","\u00e7\u0107\u010d":"c","\u017c\u017a\u017e":"z","\u015b\u015f\u0161":"s","\u00f1\u0144":"n","\u00fd\u0178":"y","\u0142":"l","\u0111":"d","\u00df":"ss","\u011f":"g","\u00de":"th"};return function(c){for(var a in d)d.hasOwnProperty(a)&&(c=
c.replace(RegExp("["+a+"]"),d[a]));return c}}();function sanitizeAndSplitTags(d,c){for(var d=$.trim(d).replace(/([A-Za-z0-9])\+(?=[A-Za-z0-9])/g,"$1 "),a=d.split(/[\s|,;]+/),b=[],f=0;f<a.length;f++){var e=StackExchange.helpers.noDiacritics(a[f].toLowerCase()).replace(/_/g,"-"),e=e.replace(RegExp("[^a-z0-9.#+"+(c?"*":"")+"-]","g"),""),e=e.replace(/^[#+-]+/,""),e=e.replace(/[.-]+$/,"");0<e.length&&-1==$.inArray(e,b)&&b.push(e)}return b}
StackExchange.question=function(){var d=function(a,b){var c=null!=a;a||(a=$('div.question div.post-menu a:contains("link")'));var e=a.closest(".post-menu, .help-menu");if(a.hasClass("share-link"))e.find(".close-share-tip").click();else{a.addClass("share-link");var d=a.attr("id").substring(10),f=a.closest(".col-section").length?"section":a.closest("div.question").length?"question":"answer",g=$('<div class="share-tip" style="display:none">share a link to this '+f+'<input type="text" value="http://'+
document.location.host+a.attr("href")+'" style="display:block; width:292px;"><a class="close-share-tip" style="float:right">close</a></div>');b&&g.find(".close-share-tip").before('<a id="link-post-'+d+'" style="float:left">cite</a>');g.appendTo(e).fadeIn(c?"fast":0).bind("removing",function(){a.removeClass("share-link")}).find(".close-share-tip").click(function(){g.fadeOutAndRemove()}).end().find("input[type=text]").select()}},c=function(a){var b=$("#post-form h2:first"),c=b.wrap("<div />").parent(),
e=c.wrap("<div />").parent(),d=$("<div />").prependTo(e),f=e.height(),g=$("<div />"),a=$(a),i=parseInt(b.css("margin-bottom")),j=$("#content"),k=$("#wmd-input").outerWidth(),r=j.offset().left>b.offset().left-5&&"visible"!=j.css("overflow-x");g.css({height:0,overflowY:"hidden"}).appendTo(c).append(a);e.css({height:f,position:"relative"});c.css({position:"absolute",bottom:-i,width:k});d.addClass("answer-help-background").css({position:"absolute",bottom:-i,height:0,width:k});r&&(d.css("left",0),c.animate({paddingLeft:5},
1E3));g.animate({height:a.height()+i+10},1E3);d.animate({height:a.height()+i+10+f},1E3);$("<div style='float:right;margin-top:10px;'><a href='#'>ok</a></div>").hide().prependTo(c).fadeIn(1E3).find("a").one("click",function(a){var e=$(this).parent();setTimeout(function(){e.remove()},1);g.animate({height:0},1E3,function(){g.add(d).remove();b.unwrap().unwrap()});d.animate({height:0},1E3);r&&c.animate({paddingLeft:0},1E3);a.preventDefault()})},a=function(){$.get("/posts/answer-help").then(c)},b,f,e,g=
function(){var a=window.location.href;0>a.indexOf("#")||(a=a.match(/#(\d+|comment(\d+)_(\d+))/i))&&(a[2]?i(a[2],a[3]):j($(".answer[data-answerid="+a[1]+"]")))},i=function(a,b){var c="#comment-"+a,e=$(c);e.length?j(e):StackExchange.comments.loadAll($("#comments-link-"+b)).done(function(){j($(c))})},j=function(a){var c=e;a.css({backgroundColor:b}).animate({backgroundColor:c},2E3,"linear",function(){$(this).css("background-color","")});a.is(".comment")&&a[0].scrollIntoView(!0)},k=function(a){a=a||{};
$('.post-menu a:contains("link")').live("click",function(b){if(!b.ctrlKey&&!b.metaKey)return d($(this),a.showCitation),!1})};return{showShareTip:d,getQuestionId:function(a){a=(a?a.closest(".question"):$(".question")).data("questionid");if(!a)throw Error("getQuestionId could not find an id");return a},highlightComment:i,initShareLinks:k,canViewVoteCounts:function(){return f},init:function(c){StackExchange.question.fullInit?StackExchange.question.fullInit(c):StackExchange.question.bindAnonymousVoteDisclaimers();
StackExchange.comments.init({autoShowCommentHelp:c.autoShowCommentHelp});c.showShareTip&&d();$("input.anon-vote").live("click",function(){var a=$(this),b=a.postId(),c=a.parent();c.closest(".question,.answer").unbind("mouseenter.helpful").unbind("mouseleave.helpful");c.text("sending feedback ...");setTimeout(function(){c.text("Thank you for your feedback.")},500);$.ajax({type:"POST",url:"/vote/anon/"+b,data:{votetypeid:"Yes"==a.val()?2:3},complete:function(){}})});var i=$(".was-this-helpful"),j=i.css("color"),
m=$(".post-text").css("color");i.each(function(){var a=$(this),b=a.text();a.closest(".answer, .question").bind("mouseenter.helpful",function(){a.html("Was this post useful to you? &nbsp;&nbsp;<input style='display:none;' class='anon-vote' type='button' value='Yes'/> &nbsp;<input style='display:none;' class='anon-vote' type='button' value='No'/>").animate({color:m},"fast","linear").find("input").fadeIn("fast")}).bind("mouseleave.helpful",function(){a.text(b).animate({color:j},"fast","linear")})});
k(c);if(c.showAnswerHelp)$("#wmd-input").one("focus",a);c.showCitation&&$("div.share-tip a[id^='link-post-']").live("click",function(){$(this).closest(".post-menu").find(".close-share-tip").click();citation.show($(this))});e=c.backgroundColor;b=c.highlightColor;f=c.canViewVoteCounts;g(c)}}}();
StackExchange.question.bindAnonymousVoteDisclaimers=function(){function d(c){return function(a){var b='Please <a href="/users/login?returnurl='+escape(document.location)+'">login or register</a> to '+c+" this post.";StackExchange.helpers.showErrorPopup($(this).parent(),b);var b="",d=$(this).prop("className"),e=$(this).closest(".answer").length?"answer":"question";/vote-up/.test(d)?b="?vote=up&type="+e:/vote-down/.test(d)?b="?vote=down&type="+e:/star/.test(d)&&(b="?vote=favorite");StackExchange.helpers.fireAndForget("/analytics/user/try-vote"+
b);a.preventDefault()}}$(".vote-up-off, .vote-down-off").click(d("vote for"));$("div.post-menu a[id^='flag-post-']").unbind("click").click(d("flag"));$(".star-off:not(.disabled)").live("click",d("favorite"))};
StackExchange.comments=function(){function d(a,b){this.postId=a;this.jDiv=b;this.jCommentsLink=$("#comments-link-"+a)}function c(a){var c=(a.constructor===$?a:$(a)).closest(".question, .answer, div[id^='post-']").find(".comments"),a=c.attr("id").replace(/^comments-/,"");if(b[a])return b[a];c=new d(a,c);return b[a]=c}function a(){if(0!=$(".question[data-questionid]").length){var a=StackExchange.question.getQuestionId();$(".comment .comment-date > span").each(function(){var b=$(this),c=b.closest(".answer"),
c=c&&c.length?c.data("answerid"):0,d=b.closest(".comment").attr("id").substr(8);b.wrap('<a class="comment-link" onclick="StackExchange.question.highlightComment({cid}, {aid})" href="{hash}"></a>'.format({hash:"#comment"+d+"_"+(c?c:a),cid:d,aid:c}))})}}var b={},f=function(){};d.prototype={checkDiscussion:f,ensureInput:f,commentsShown:function(){this.jCommentsLink.hide();this.jCommentsLink.data("comments-count",0)},addShow:function(a){var b=this;this.loadAllComments().done(function(){b.jCommentsLink.hide();
b.checkDiscussion()});var c=this.ensureInput();c&&!a&&c.focus()},ajax:function(a,b,c,d){c&&!d&&StackExchange.helpers.addSpinner(c,{"margin-left":"10px"});var f=this;return $.ajax(a).fail(function(a){$(".error-notification").fadeOut("fast",function(){$(this).remove()});a=a.responseText;if(!a||100<=a.length)a="An error occured"+(b?" "+b:"");StackExchange.helpers.showErrorPopup(c||f.jDiv,a);c&&!d&&StackExchange.helpers.removeSpinner()}).done(StackExchange.helpers.removeSpinner).promise()},showComments:function(b){this.jDiv.find(" > table > tbody").html(b);
this.jCommentsLink.text("add comment");"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);a();this.commentsShown()},loadAllComments:function(a){this.jDiv.removeClass("dno");if(!a&&!/more comment/.test($("#comments-link-"+this.postId).text()))return $.Deferred().resolve().promise();var b=this;return this.ajax({type:"GET",url:"/posts/"+this.postId+"/comments",dataType:"html"},"while fetching comments").done(function(a){b.showComments(a)}).promise()}};return{init:function(b){b=b&&
b.post||document;$("a[id^='comments-link-']",b).click(function(){var a=/more comment/.test($(this).text());c(this).addShow(a)});b==document&&a()},loadAll:function(a){return c(a).loadAllComments(!0)},extendPostUi:function(a){for(var b in a)a.hasOwnProperty(b)&&(d.prototype[b]=a[b])},uiForPost:c}}();
StackExchange.share=function(){function d(a,b,c){window.open(a,b,c)||(window.location.href=a)}function c(a,b){var c=a.indexOf("?"),e=a.indexOf("#");return-1==c?-1==e?a+"?"+b:a.substring(0,e)+"?"+b+a.substring(e):-1==e?a+"&"+b:a.substring(0,e)+"&"+b+a.substring(e)}return{gplus:function(a,b){b=c(b,"sgp=1");a.click(function(){d("https://plus.google.com/share?url="+b,"sharegplus","toolbar=1,status=1,resizable=1,scrollbars=1,width=600,height=500")})},twitter:function(a,b,f){b=c(b,"stw=1");a.click(function(){d("http://twitter.com/share?url="+
b+"&ref=twitbtn&text="+f,"sharetwitter","toolbar=1,status=1,resizable=1,scrollbars=1,width=800,height=526")})},facebook:function(a,b,f){b=c(b,"sfb=1");a.click(function(){d("http://www.facebook.com/sharer.php?u="+b+"&ref=fbshare&t="+f,"sharefacebook","toolbar=1,status=1,resizable=1,scrollbars=1,width=626,height=436")})}}}();
function initTagRenderer(d,c){window.tagRenderer||(window.tagRendererRaw=function(a,b){var b=b||"",f="";b||(d&&-1<$.inArray(a,d)?f=" required-tag":c&&-1<$.inArray(a,c)&&(f=" moderator-tag"));return"<a class='post-tag"+f+"' href='"+b+"/questions/tagged/"+encodeURIComponent(a)+"' title=\"show questions tagged '"+a+"'\" rel='tag'>"+a+"</a>"},window.tagRenderer=function(a,b){return $(tagRendererRaw(a,b))})}
function showFadingHelpText(d){d.wrap('<div class="dno" />').show().parent().fadeIn("slow",function(){$(this).children().unwrap()})}
function initFadingHelpText(){var d={"wmd-input":"#how-to-format",tagnames:"#how-to-tag","tag-editor":"#how-to-tag",title:"#how-to-title"},c=$("#wmd-input, #tagnames, #title, .tag-editor input"),a=function(a){return $(a).parent().hasClass("tag-editor")?d["tag-editor"]:d[$(a).attr("id")]};c.focus(function(){var b=a(this);c.each(function(){var c=a(this);c!=b&&$(c).hide()});var d=$(b);d.is(":visible")||showFadingHelpText(d)})}
$.fn.extend({postId:function(){var d=this.first();if(!d.hasClass("answer")||!d.hasClass("question"))d=d.closest(".answer, .question");return parseInt(d.find(".vote input")[0].value)}});
StackExchange.newsletterAd=function(){function d(a){a=$('<div id="lightbox-panel" class="popup" style="display:block"></div>').append('<div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div>').append(a);$('<div id="lightbox"></div>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");a.appendTo($("body")).center().fadeIn("fast").find(".popup-close").click(function(){$("#lightbox, #lightbox-panel").fadeOutAndRemove()})}function c(){var a=StackExchange.options.site.name,
b=$(['<div style="text-align: left;">','<h2 style="margin-bottom: 15px;">Subscribe to the '+a+" weekly newsletter</h2>",'<p><strong><a href="/users/login?returnurl=/newsletter/signup/redirect">Create an account on '+a+'</a> or <a href="/users/login?returnurl=/newsletter/signup/redirect">log in</a> if you already have one.</strong></p>','<form><label for="newsletter-email-input">Or, send newsletter emails to:</label> <input type="text" id="newsletter-email-input" maxlength="100" title="your email address" /> <input type="submit" value="Subscribe" id="newsletter-email-submit" /></form></div>'].join(""));
b.find("form").submit(function(){var a=$(this),c=$.trim(b.find("#newsletter-email-input").val());if(0==c.length)return!1;StackExchange.helpers.addSpinner(a);$.ajax({url:"/newsletter/signup/anon",type:"POST",dataType:"json",data:{email:c},success:function(b){"confirmed"==b.status&&!b.error?(a.find("#newsletter-email-input").attr("disabled",!0),a.find("#newsletter-email-submit").replaceWith('<span style="line-height: 120%; text-align: center;"><strong>Subscribed!</strong></span>'),$("#newsletter-signup-container").replaceWith('<div style="line-height: 200%; text-align: center;"><strong>Subscribed!</strong></div>')):
"unconfirmed"==b.status&&!b.error?(a.find("#newsletter-email-input").attr("disabled",!0),a.find("#newsletter-email-submit").replaceWith('<span style="line-height: 120%; text-align: center;"><strong>Subscribed!</strong></span>'),a.append("<br /><br/><p><em>Please click the link in the confirmation email to activate your subscription.</em></p>"),$("#newsletter-signup-container").replaceWith('<span style="line-height: 120%;"><strong>Success!</strong> Please click the link in the confirmation email to activate your subscription.</span>')):
a.showErrorPopup(b.error||"there was a problem signing up for the newsletter<br />please try again later")},error:function(){a.showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},complete:function(){StackExchange.helpers.removeSpinner(a)}});return!1});d(b)}return{init:function(){$("#newsletter-signup").click(function(){var a=$(this);if(StackExchange.options.user.isAnonymous)return c(),!1;StackExchange.helpers.addSpinner("#newsletter-signup-container");
$.ajax({url:"/newsletter/signup",type:"POST",dataType:"json",success:function(b){b.url?window.location.href=b.url:"confirmed"==b.status?$("#newsletter-signup-container").replaceWith('<div style="line-height: 200%; text-align: center;"><strong>Subscribed!</strong></div>'):"unconfirmed"==b.status?$("#newsletter-signup-container").replaceWith('<span style="line-height: 120%;"><strong>Success!</strong> Please click the link in the confirmation email to activate your subscription.</span>'):a.parent().showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},
error:function(){a.parent().showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},complete:function(){StackExchange.helpers.removeSpinner("#newsletter-signup-container")}})});$("#newsletter-preview").click(function(){var a=$(window).height(),a=Math.min(600,a-100),a=['<div id="newsleter-preview-pane" style="overflow: hidden; width: 660px; height: ',a,'px;"><iframe src="',$(this).attr("href"),'" width="660" height="',a,'" frameborder="0"></iframe></div>'].join("");
d(a);return!1})},loader:function(a,b){var a=b||a,c=$(".newuser-greeting");$.ajax({url:"/newsletter/targetted/ajax",data:{domain:a},success:function(a){$("#newsletter-ad").remove();c.empty().append($(a))},complete:function(){c.attr("class","").attr("style","")}});b||(window.sessionStorage.tNewsletter=a+"-continued")}}}();
(function(d,c,a,b){d.fn.caret=function(f,e){var g,i,j=this[0],k=d.browser.msie;"object"===typeof f&&"number"===typeof f.start&&"number"===typeof f.end?(g=f.start,i=f.end):"number"===typeof f&&"number"===typeof e?(g=f,i=e):"string"===typeof f?-1<(g=j.value.indexOf(f))?i=g+f[c]:g=null:"[object RegExp]"===Object.prototype.toString.call(f)&&(f=f.exec(j.value),null!=f&&(g=f.index,i=g+f[0][c]));if("undefined"!=typeof g)return k?(k=this[0].createTextRange(),k.collapse(!0),k.moveStart("character",g),k.moveEnd("character",
i-g),k.select()):(this[0].selectionStart=g,this[0].selectionEnd=i),this[0].focus(),this;if(k)if(i=document.selection,"textarea"!=this[0].tagName.toLowerCase()){k=this.val();g=i[a]()[b]();g.moveEnd("character",k[c]);var h=""==g.text?k[c]:k.lastIndexOf(g.text);g=i[a]()[b]();g.moveStart("character",-k[c]);var n=g.text[c]}else g=i[a](),i=g[b](),i.moveToElementText(this[0]),i.setEndPoint("EndToEnd",g),h=i.text[c]-g.text[c],n=h+g.text[c];else h=j.selectionStart,n=j.selectionEnd;g=j.value.substring(h,n);
return{start:h,end:n,text:g,replace:function(a){return j.value.substring(0,h)+a+j.value.substring(n,j.value[c])}}}})(jQuery,"length","createRange","duplicate");
